export type ToLetTableResponseModel = {
  id: string;
  title: string;
  personId: string;
  rent: number;
  isRentNegotiable: boolean;
  availableFrom: string;
  description: string;
  floorNumber: number;
  totalFloor: number;
  numberOfBed: number;
  numberOfBath: number;
  areaInSqFeet: number;
  isBachelorAllowed: boolean;
  hasParking: boolean;
  hasGenerator: boolean;
  rentTypeId: number;
  careTakerName: null | string;
  careTakerPhone: null | string;
  amenities: string;
  flatViewId: number;
  landMarkId: number[];
  villageId: string;
  villageName: string;
  upazila: number;
  district: number;
  isActive: boolean;
  owner: string;
  rentTypeName: string;
};

export type ToLetDetailResponseModel = {
  title:             string;
  personId:          string;
  owner:             string;
  rent:              number;
  isRentNegotiable:  boolean;
  availableFrom:     Date;
  description:       string;
  floorNumber:       number;
  totalFloor:        number;
  numberOfBed:       number;
  numberOfBath:      number;
  areaInSqFeet:      number;
  isBachelorAllowed: boolean;
  hasParking:        boolean;
  hasGenerator:      boolean;
  rentTypeId:        number;
  rentTypeName:      string;
  careTakerName:     string;
  careTakerPhone:    string;
  amenities:         string[];
  flatViewId:        number;
  landMarkId:        number[];
  villageId:         string;
  villageName:       string;
  upazilaId:         number;
  districtId:        number;
  isActive:          boolean;
  id:                string;
};

