export type FavoriteRequestType = {
  cloth: string;
  bird: string;
  animal: string;
  food: string;
  pet: string;
  fish: string;
  fruit: string;
  vehicle: string;
  book: string;
  sport: string;
  movie: string[];
  website: string;
  cooking: string[];
  game: string[];
  music: string[];
  read: string[];
  tvShow: string[];
  personId: string;
};

export type FavoriteResponseType = {
  cloth: string;
  bird: string;
  animal: string;
  food: string;
  pet: string;
  fish: string;
  fruit: string;
  vehicle: string;
  book: string;
  sport: string;
  movie: string[];
  website: string;
  cooking: string[];
  game: string[];
  music: string[];
  read: string[];
  tvShow: string[];
  personId: string;
};
